---
- import_playbook: destroy-playbooks/destroy-ubuntu-template.yaml
- import_playbook: destroy-playbooks/destroy-gpu-passthrough.yaml



- name: Final local setup
  hosts: localhost
  tasks:
    - name: Remind user to source environment
      debug:
        msg: "Setup Complete! Run 'source ./setup_terraform_env.sh' to start using Terraform."