[proxmox_nodes]
legion-node-01 ansible_host=172.16.0.10
prodesk-node-02 ansible_host=172.16.0.15
venue-node-03 ansible_host=172.16.0.20

[proxmox_nodes:vars]
ansible_user=root

# Add this group so the Playbook knows where the API Master is
[proxmox_master]
prodesk-node-02

[ml_workers]
ml-gpu-worker-legion ansible_host=172.16.0.101

[ml_workers:vars]
ansible_user=ubuntu

[gitlab_servers]
gitlab-server ansible_host=172.16.0.102

[gitlab_servers:vars] 
ansible_user=ubuntu


[k3s_servers]
k3s-master-venue ansible_host=172.16.0.103
k3s-worker-prodesk ansible_host=172.16.0.104

[k3s_servers:vars] 
ansible_user=ubuntu





