[proxmox_nodes]
legion-node-01 ansible_host=172.16.0.10
prodesk-node-02 ansible_host=172.16.0.15
venue-node-03 ansible_host=172.16.0.20

# Add this group so the Playbook knows where the API Master is
[proxmox_master]
legion-node-01

[proxmox_nodes:vars]
ansible_user=root