---
- import_playbook: 01-node-playbooks/01-proxmox_bootstrap.yaml
- import_playbook: 01-node-playbooks/02-create_ubuntu_templates.yaml
- import_playbook: 01-node-playbooks/03-gpu_passthrough.yaml

- name: Final local setup
  hosts: localhost
  tasks:
    - name: Remind user to source environment
      debug:
        msg: "Setup Complete! Run 'source ./setup_terraform_env.sh' to start using Terraform."