# --- SECTION 2: LEGION NODE (GPU PASSTHROUGH) ---
    
    - name: Blacklist all NVIDIA and i2c drivers
      copy:
        dest: /etc/modprobe.d/blacklist.conf
        content: |
          blacklist nvidia
          blacklist nvidia-drm
          blacklist nvidia-modeset
          blacklist nvidia-uvm
          blacklist nouveau
          blacklist i2c_nvidia_gpu
          blacklist i2c_ccgx_ucsi
          blacklist ucsi_ccg
          blacklist snd_hda_intel
          blacklist snd_hda_codec_hdmi
      when: inventory_hostname == 'legion-node-01'


    - name: Hard-Disable NVIDIA Drivers  in GRUB
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt pcie_acs_override=downstream,multifunction video=efifb:off initcall_blacklist=sysfb_init module_blacklist=nvidia,nvidia_drm,nvidia_modeset,nvidia_uvm,nouveau,i2c_nvidia_gpu"'
      register: grub_config
      when: inventory_hostname == 'legion-node-01'

    - name: Update GRUB
      command: update-grub
      when: 
        - inventory_hostname == 'legion-node-01'
        - grub_config.changed

    - name: Stub GPU and USB Controller for VFIO
      copy:
        dest: /etc/modprobe.d/vfio.conf
        content: |
          # 1660 Ti GPU and USB Controller
          options vfio-pci ids=10de:2191,10de:1aeb,10de:1aec,10de:1aed disable_vga=1
          softdep i2c_nvidia_gpu pre: vfio-pci
      register: vfio_config
      when: inventory_hostname == 'legion-node-01'

    - name: Ensure VFIO modules load at boot
      lineinfile:
        path: /etc/modules
        line: "{{ item }}"
      loop:
        - vfio
        - vfio_iommu_type1
        - vfio_pci
        - vfio_virqfd
      register: modules_config
      when: inventory_hostname == 'legion-node-01'

    - name: Rebuild Initramfs on Change
      command: update-initramfs -u -k all
      when: 
        - inventory_hostname == 'legion-node-01'
        - (vfio_config.changed or modules_config.changed or grub_config.changed)